name: comment_tree
description: Render comment tree like facebook comment - reply.

version: 0.3.0

homepage: https://github.com/dangngocduc/comment_tree

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
